feat: update card to images
AGF-Equipamentos/quartz-client pull request #43
Opened 2023-07-11 19:43 UTC by kevinpetroni

2023-07-12 18:10 UTC, ArthurPedroti requested changes

2023-07-12 18:10 UTC, ArthurPedroti commented on .env
> +NEXT_PUBLIC_APP_NAME=quartz
remover variaveis ambientes

```suggestion
NEXT_PUBLIC_API_HOST=
NEXT_PUBLIC_APP_NAME=
```

2023-07-12 18:10 UTC, ArthurPedroti commented on next.config.js
> +        hostname: 'agf-quartz.s3.amazonaws.com'
Transformar em variabel ambiente
```suggestion
        hostname: process.env.IMAGES_HOSTNAME
```

2023-07-12 18:10 UTC, ArthurPedroti commented on src/components/WorkstationCard/index.tsx
> +// import { Image } from '@chakra-ui/react'
remover comentario

2023-07-12 18:10 UTC, ArthurPedroti commented on src/components/WorkstationCard/index.tsx
> -import torno_cnc from '../../assets/torno_cnc.png'
deletar arquivo que ficou na pasta assets

2023-07-12 18:10 UTC, ArthurPedroti commented on src/components/WorkstationCard/index.tsx
> +                      src={disponibility.attributes.cover.data.attributes.url} // disponibility.att..cover..
tirar esse comentario

2023-07-12 19:17 UTC, ArthurPedroti commented on next.config.js
> +        hostname: 'process.env.IMAGES_HOSTNAME'
Vc testou isso? pq não funciona

2023-07-12 19:24 UTC, kevinpetroni commented on next.config.js
> +        hostname: 'process.env.IMAGES_HOSTNAME'
não era pra alterar do jeito que estava pro exemplo? o modo como estava funcionando era o seguinte:  hostname: 'agf-quartz.s3.amazonaws.com'

2023-07-12 19:26 UTC, kevinpetroni commented on .env
> +NEXT_PUBLIC_APP_NAME=
Isso eu não entendi, eu volto como era 
![image](https://github.com/AGF-Equipamentos/quartz-client/assets/124711123/715f61c3-a60c-4740-aa6e-c8b583782a81)

2023-07-12 20:58 UTC, ArthurPedroti requested changes

2023-07-12 20:58 UTC, ArthurPedroti commented on .env
> +IMAGES_HOSTNAME=
``Adicinar essa variavel ambiente ao arquivos de ci:
![image](https://github.com/AGF-Equipamentos/quartz-client/assets/52859409/16eb6a83-122c-4539-88b5-969cc8076b59)

Ex: 
```
      env:
        NEXT_PUBLIC_API_HOST: ${{ secrets.NEXT_PUBLIC_API_HOST }}
        NEXT_PUBLIC_APP_NAME: quartz
        IMAGES_HOSTNAME: ${{ secrets.IMAGES_HOSTNAME }}
```

E depois adicionar essa env nos secrets do repositorio do github.

2023-07-13 18:39 UTC, ArthurPedroti requested changes

2023-07-13 18:39 UTC, ArthurPedroti commented on .github/workflows/pr_main.yml
> +          IMAGES_HOSTNAME: ${{ secrets.IMAGES_HOSTNAME }}
Por que alterou a indentação do arquivo inteiro? arquivos yml não pode alterar a indentação, era só para adicionar 1 linha
Precisa adicionar a mesma 1 linha no arquivo prod_main.yml

2023-07-14 13:14 UTC, ArthurPedroti approved these changes

2023-07-14 13:14 UTC, merged